HabitHive/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('', include('habits.urls')),
    path('analytics/', include('analytics.urls')),
]

analytics/urls.py
# urls.py in analytics app
from django.urls import path
from . import views

app_name = 'analytics'

urlpatterns = [
    path('overall/', views.overall_analytics, name='overall_analytics'),
    path('habit/<int:habit_id>/', views.habit_analytics, name='habit_analytics'),
]

habits/urls.py
from django.urls import path
from . import views

app_name = 'habits'


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('create/', views.create_habit, name='create_habit'),
    path('delete/<int:habit_id>/', views.delete_habit, name='delete_habit'),
    path('mark-log/<int:habit_id>/', views.mark_log, name='mark_log'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('delete-account/', views.delete_account, name='delete_account'),

    path('logout/',views.logout_view,name='logout'),
    path('login/',views.login_view,name='login'),
]

habits/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django.utils.timezone import now
from datetime import timedelta
from django.contrib.auth.models import User

UserModel = get_user_model() # dyanamically get the user model


class Habit(models.Model):
    CATEGORY_CHOICES = [
        ('fitness','Fitness'),
        ('learning','Learning'),
        ('health','Health'),
        ('productivity','Productivity'),
        ('personal_development','Personal Development'),
        ('financial','Financial'),
        ('environmental','Environmental'),
        ('creative','Creative'),
        ('social','Social'),
        ('spiritual','Spiritual'),
        ('professional','Professional'),
    ]

    FREQUENCY_CHOICES = [
        ('daily','Daily'),
        ('weekly','Weekly'),
        ('monthly','Monthly'),
        ('custom','Custom'),
    ]

    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name='habits')
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True,null=True)
    category = models.CharField(max_length=50,choices=CATEGORY_CHOICES)
    duration = models.PositiveIntegerField(help_text="No. of repetitions.") # value for duration.
    frequency = models.CharField(max_length=20,choices=FREQUENCY_CHOICES,default='daily') 
    custom_days_gap = models.PositiveIntegerField(blank=True,null=True,help_text="In days. (Custom Frequency)")
    count = models.IntegerField(default=0) # no of times completed.
    streak = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    nxt_task_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} [{self.category}]'
    
    def set_remainder(self,flag=False): # set remainder date for the user on the day of activity | call every time the remainder date is reached.
        if self.frequency == 'daily':
            next_in = 1 # task to be completed next in ( how many days ) - calculated for remiander and streak checking.
        elif self.frequency == 'weekly':
            next_in = 7
        elif self.frequency == 'monthly':
            next_in = 30
        elif self.frequency == 'custom' and self.custom_days_gap:
            next_in = self.custom_days_gap
        else:
            next_in = 1 # default
        # updating remainder date

        if flag: # flag active when date is reset to now.
            self.nxt_task_at = now() + timedelta(days=next_in)
        else:
            self.nxt_task_at = self.nxt_task_at + timedelta(days=next_in)
        self.save()


    def calculate_progress(self, completed_tasks):
        progress =  (completed_tasks / self.duration) * 100 
        return round(min(progress,100), 2)





habits/forms.py
from django import forms
from .models import Habit

class HabitForm(forms.ModelForm):
    class Meta:
        model = Habit
        fields = ['name','description','category','duration','frequency','custom_days_gap',]

        widgets = {
            'category':forms.Select(attrs={'class': 'form-control'}),
            'frequency':forms.Select(attrs={'class': 'form-control'}),
            'duration':forms.NumberInput(attrs={'placeholder':'How long to be done, if weekly then 2 week etc. [Only Number]'}),
            'custom_days_gap':forms.NumberInput(attrs={'placeholder':'Only for custom frequency'}),

        }

habits/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils.timezone import now
from .models import Habit
from analytics.models import OverallAnalytics
from .forms import HabitForm
from datetime import timedelta
from django.db import models
import random
from django.db.models.signals import post_save


# message to be shown when user completes a task
motivational_messages = [
    "Keep going, you're doing great!",
    "Believe in yourself and all that you are!",
    "Small steps every day lead to big changes.",
    "Consistency is the key to success.",
    "Your future self will thank you for the effort you put in today.",
    "Every habit you create brings you closer to your goals.",
    "Don't watch the clock; do what it does. Keep going.",
    "Your only limit is you. Push past it!",
    "Celebrate every small victory along the way.",
    "Make today so awesome that yesterday gets jealous.",
    "You are capable of amazing things.",
    "Start where you are. Use what you have. Do what you can.",
    "Success doesn’t come from what you do occasionally; it comes from what you do consistently.",
    "Dream big. Start small. Act now.",
    "Progress is progress, no matter how small.",
    "Stay positive, work hard, make it happen.",
    "The secret of getting ahead is getting started.",
    "You don’t have to be perfect to be amazing.",
    "Motivation gets you started, but habit keeps you going.",
    "Don’t give up. Great things take time."
]

@login_required
def dashboard(request):
    user_habits = Habit.objects.filter(user=request.user, is_active=True)
    # highest streak implementation
    analytics = get_object_or_404(OverallAnalytics,user=request.user)
    highest_streak = analytics.highest_streak
    remainder_habits = []
    notification = []
    # check remainder and streak updates
    for habit in user_habits:
        if habit.nxt_task_at.date() == habit.created_at.date():
            habit.set_remainder()
            print(f'Next date updated for habit {habit.name}')
        if habit.nxt_task_at.date() == now().date():
            remainder_habits.append(f'Remainder: Do not forget to complete today`s task "{habit}".')
        elif habit.nxt_task_at.date() < now().date() and habit.streak:
            remainder_habits.append(f"You have lost your streak of habit '{habit}' :(")
            habit.streak = False
            habit.save()
            # manual trigger for analytics:signals
            post_save.send(sender=Habit, instance=habit, task_missed=True)

            habit.set_remainder()

    # progress calculation
    progress_data = []
    for habit in user_habits:
        progress = habit.calculate_progress(habit.count)
        progress_data.append({
            'habit':habit,
            'progress':progress
        })
        # notification when progress is 100%
        if progress == 100:
            notification.append(f"Congratulations! You've acheived your goal for {habit.name}!")
            habit.is_active = False
            habit.save()
            post_save.send(sender=Habit, instance=habit, habit_completed=True)

    # data for dashboard sections
    category_data = Habit.objects.filter(user=request.user, is_active=True).values('category').annotate(count=models.Count('category'))
    category_labels = [entry['category'].capitalize() for entry in category_data]
    category_values = [int(entry['count']) for entry in category_data]


    context = {
        'reminder_habits':remainder_habits,
        'notification':notification,
        'category_labels':category_labels,
        'category_values':category_values,
        'total_habits':len(user_habits),
        'progress_data':progress_data[:5],
        'habit_gems': sum(habit.count for habit in user_habits),
        'habit_cards':user_habits,
        'motivational_message': random.choice(motivational_messages),
        'highest_streak':highest_streak,
    }

    return render(request, 'habits/dashboard.html', context)

@login_required
def create_habit(request):
    if request.method == 'POST':
        form = HabitForm(request.POST)
        if form.is_valid():
            habit = form.save(commit=False)
            habit.user = request.user
            print(request.user)
            habit.save()
            # manual trigger for initializing a habit analytics database
            post_save.send(sender=Habit, instance=habit, habit_initialized=True)
            return redirect('habits:dashboard')
        else:
            print(form.errors)
    else:
        form = HabitForm()
    return render(request, 'habits/create_habit.html', {'form': form})

@login_required
def delete_habit(request, habit_id):
    habit = get_object_or_404(Habit, id=habit_id, user=request.user)
    if request.method == 'POST':
        habit.is_active = False
        habit.save()
        return redirect('habits:dashboard')
    return render(request, 'habits/delete_habit.html', {'habit': habit})

@login_required
def mark_log(request, habit_id):
    habit = get_object_or_404(Habit, id=habit_id, user=request.user)
    print(habit.name)
    if request.method == 'POST':
        habit.count += 1
        flag = request.POST.get('reset_and_log') == 'True'
        if flag:
            habit.set_remainder(True) # next task date reset.
        else:
            habit.set_remainder()
        habit.save()
        # manual trigger for analytics:signals
        post_save.send(sender=Habit, instance=habit, task_marked=True)
        return redirect('habits:dashboard')
    else:
        if habit.nxt_task_at.date() == now().date():
            message = f"Are you ready to mark today’s habit as complete? Tap 'Confirm' to log your progress!"
            context = {
                'message':message,
                'flag':False,
                'habit':habit,
            }
        else:
            message = f"Your next scheduled activity for this habit is on {habit.nxt_task_at.date()}. Would you like to reset it and log today's progress?"
            context = {
                'message':message,
                'flag':True,
                'habit':habit,
            }
    return render(request, 'habits/mark_log.html', context)

habits/templates/habits/create_habit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'habits/css/create_habit.css' %}?v=3">
<div class="create-habit-container">
    <div class="form-header">
        <h2>Create a New Habit</h2>
        <p>Define your habit, set its details, and start building consistency!</p>
    </div>
    <form method="POST" class="create-habit-form">
        {% csrf_token %}
        {{ form.non_field_errors }}
        
        <div class="form-group">
            <label for="id_name">Habit Name:</label>
            {{ form.name }}
        </div>

        <div class="form-group">
            <label for="id_description">Description:</label>
            {{ form.description }}
        </div>

        <div class="form-group">
            <label for="id_category">Category:</label>
            {{ form.category }}
        </div>

        <div class="form-group">
            <label for="id_duration">Duration (in days):</label>
            {{ form.duration }}
        </div>

        <div class="form-group">
            <label for="id_frequency">Frequency:</label>
            {{ form.frequency }}
        </div>

        <div class="form-group">
            <label for="id_custom_days_gap">Custom Days Gap (if applicable):</label>
            {{ form.custom_days_gap }}
        </div>

        <div class="form-buttons">
            <button type="submit" class="btn btn-primary">Save Habit</button>
            <a href="{% url 'habits:dashboard' %}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

habits/templates/habits/dashboard.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'habits/css/styles.css' %}?v=4">
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0"></script>
<div class="dashboard-container">
    <!-- Notifications -->
    <div class="notifications">
        {% if notifications or reminder_habits %}
        {% for notification in notifications %}
        <b style="color: #13b12a;">{{ notification }}</b>
        {% endfor %}
        {% for reminder in reminder_habits %}
        <b style="color: #e31919;">{{ reminder }}</b>
        {% endfor %}
        {% else %}
        <b>{{ motivational_message }}</b>
        {% endif %}
    </div>

    <!-- Section 1: Overview -->
    <div class="overview">
        <h3>Your Habits Overview</h3>
        <div class="pie-chart-section">
            {% if category_labels and category_values %}
                <canvas id="pieChart"></canvas>
            {% else %}
                <p>No data to display.</p>
            {% endif %}
        </div>
        <div class="overview-titles">
            <h3> Your Profile </h3>
            <p><b>Total Active Habits:</b> {{ total_habits }}</p>
            <p><b>Habit Gems Collected:</b> {{ habit_gems }}</p>
            <p><b>Highest Streak:</b> {{ highest_streak }}</p>
            <a href="{% url 'analytics:overall_analytics' %}" class="btn">Analytics</a> <!--[analytics:analytics_dash]-->
        </div>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var ctx = document.getElementById('pieChart').getContext('2d');
            var chart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: {{ category_labels|safe|default:"[]" }},
                    datasets: [{
                        data: {{ category_values|safe|default:"[]" }},
                        backgroundColor: ['#FF5733', '#33FF57', '#3357FF','#FF33A6','#57FF33','#5733FF','#33FFA6','#FF5733','#33A6FF','#A633FF','#FF33C1'],
                    }]
                },
                options: {
                    responsive: true,
                    plugins: {
                        legend: {
                            position: 'top',
                        },
                        tooltip: {
                            callbacks: {
                                label: function(tooltipItem) {
                                    var dataset = tooltipItem.chart.data.datasets[0];
                                    var total = dataset.data.reduce(function(previousValue, currentValue) {
                                        return previousValue + currentValue;
                                    }, 0);
                                    var currentValue = dataset.data[tooltipItem.dataIndex];
                                    var percentage = Math.floor(((currentValue / total )* 100) + 0.5); 
                                    return ' ' + percentage + '%'; 
                                }
                            }
                        },
                        datalabels: {
                            formatter: function(value, ctx) {
                                var total = 0;
                                ctx.chart.data.datasets[0].data.forEach(function(item) {
                                    total += item;
                                });
                                var percentage = (value/total * 100).toFixed(2) + '%';
                                return percentage;
                            },
                            color: '#fff',
                            anchor: 'center',
                            align: 'center'
                        }
                    }
                }
            });

            setTimeout(function() {
                var alert = document.querySelector('.notifications');
                if (alert) {
                    alert.style.opacity = 0;
                    setTimeout(function() {
                        alert.style.display = 'none';
                    }, 1000);
                }
            }, 7000);
        });
    </script>

    <!-- Section 2: Recent Progress -->
    <div class="recent-progress">
        <h3>Your Recent Habits</h3>
        <div class="progress-bars">
            {% for item in progress_data %}
            <div class="progress-item">
                <p>{{ item.habit.name }}</p>
                <p style="text-align: right;">{{ item.progress }}%</p>
                <div class="progress-bar" style="width: {{ item.progress }}%;"></div>
            </div>
            {% endfor %}
        </div>
    </div>

    <!-- Section 3: Habit Cards -->
    <div class="habit-cards">
        <h3>Your Habits</h3>
        <div class="cards-carousel">
            {% for habit in habit_cards %}
            <div class="habit-card">
                <div class="card-image" style="background-image: url('/static/habits/images/{{ habit.category }}.jpg');"></div>
                <div class="card-content">
                    <h4>{{ habit.name }}</h4>
                    <a href="{% url 'habits:mark_log' habit.id %}" class="btn">Mark Progress</a> <!--'habits:mark_log' habit.id-->
                    <a href="{% url 'analytics:habit_analytics' habit.id %}" class="btn">Habit Analytics</a> <!--'analytics:habit_analytics' habit.id-->
                    <a href="{% url 'habits:delete_habit' habit.id %}" class="btn" style="background-color: #e31919;">Delete Habit</a>
                </div>
            </div>
            {% endfor %}
        </div>
        <a href="{% url 'habits:create_habit' %}" class="btn add-habit">Add New Habit</a>
    </div>
</div>


{% endblock %}

habits/templates/habits/delete_habit.html
{% extends 'base.html' %}

{% block title %}Delete Habit{% endblock %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'habits/css/styles.css' %}">
<div class="delete-account-container">
    <h2>Delete {{ habit.name }}</h2>
    <p class="warning">
        Notice: Deleting this habit will mark it as inactive, but your data will remain intact.
    </p>
    <form method="post" action="{% url 'habits:delete_habit' habit.id %}">
        {% csrf_token %}
        <div class="form-actions">
            <button type="submit" class="btn-delete">Delete Habit</button>
            <a href="{% url 'habits:dashboard' %}" class="btn-cancel">Cancel</a> <!-- [habits:dashboard]-->
        </div>
    </form>
</div>
{% endblock %}

habits/templates/habits/mark_log.html
{% extends 'base.html' %}

{% block title %}Habit Log{% endblock %}
{% block content %}
<div class="log-container">
    <h2>Mark progress for :{{ habit.name }}</h2>
    <p class="info">
        {{message}}
    </p>
    <form method="post" action="{% url 'habits:mark_log' habit.id %}">
        {% csrf_token %}
        <div class="form-actions">
            <input type="hidden" name="reset_and_log" value="{{ flag }}">
            <button type="submit" class="btn-confirm">Confirm</button>
            <a href="{% url 'habits:dashboard' %}" class="btn-cancel">Cancel</a> <!-- [habits:dashboard]-->
        </div>
    </form>
</div>
<style>
    
/* delete account css */
.log-container {
    background: white;
    padding: 2rem;
    margin: 2rem auto;
    border-radius: 8px;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    max-width: 500px;
    text-align: center;
}

.log-container h2 {
    color: #f97400;
    margin-bottom: 1rem;
    font-size: 1.8rem;
}

.log-container .info {
    color: #ff7700;
    font-weight: bold;
    margin-bottom: 2rem;
}

.log-container .form-actions {
    display: flex;
    justify-content: space-around;
    gap: 1rem;
}

.btn-confirm {
    background-color: #3ce742;
    border: none;
    color: rgb(0, 0, 0);
    padding: 0.8rem 1.2rem;
    border-radius: 4px;
    cursor: pointer;
    font-size: 1rem;
}

.btn-confirm:hover {
    background-color: #30c735;
}

.btn-cancel {
    background-color: #ef1919;
    color: #ffffff;
    padding: 0.8rem 1.2rem;
    border-radius: 4px;
    text-decoration: none;
    font-size: 1rem;
    display: inline-block;
}

.btn-cancel:hover {
    background-color: #cc1616;
}
</style>
{% endblock %}