HabitHive/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('', include('habits.urls')),
    path('analytics/', include('analytics.urls')),
]

habits/urls.py
from django.urls import path
from . import views

app_name = 'habits'


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('create/', views.create_habit, name='create_habit'),
    path('delete/<int:habit_id>/', views.delete_habit, name='delete_habit'),
    path('mark-log/<int:habit_id>/', views.mark_log, name='mark_log'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('delete-account/', views.delete_account, name='delete_account'),

    path('logout/',views.logout_view,name='logout'),
    path('login/',views.login_view,name='login'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}HabitHive{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/styles.css' %}?v=1">
    </head>
    <body>
        <header class="header">
            <h1>Habit-Hive</h1>
            <p>A place where habits grow and thrive.</p>
            <nav>
                <ul class="nav-links">
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'habits:dashboard' %}" class="btn btn-dashboard">Dashboard</a></li> <!--[habits:dashboard]-->
                        <li><a href="{% url 'users:logout' %}" class="btn btn-logout">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'users:register' %}" class="btn btn-signup">Sign Up</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            {% block content %}
            {% endblock %}
        </main>
        <footer>
            <p>&copy; 2024 Habit-Hive</p>
        </footer>
    </body>
</html>